# Galera Client Tools
---
- name: Setup Percona Apt Key
  apt_key: id="{{ item }}" keyserver=keyserver.ubuntu.com state=present
  with_items:
    - 4d1bb29d63d98e422b2113b19334a25f8507efa5

- name: Setup Percona Apt Repository
  apt_repository: repo="{{ item }}"
  with_items:
    - "deb http://repo.percona.com/apt bionic main"
    - "deb-src http://repo.percona.com/apt bionic main"

- name: Pin Percona Repos for XtraDB
  copy: src=etc/apt/preferences.d/00percona.pref dest=/etc/apt/preferences.d/00percona.pref mode=0644 owner=root group=root

- name: Install Percona XtraDB client
  apt: pkg="{{ item }}" state=present
  with_items:
    - percona-xtradb-cluster-client-5.7
